apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
spec:
  accessModes:
  {{- range .Values.pvc.accessModes }}
    - {{ . }}
  {{- end }}
  volumeMode: {{ .Values.pvc.volumeMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
