apiVersion: v2
appVersion: 0.17.0
description: A Helm chart for NATS Streaming
icon: https://nats.io/img/nats-icon-color.png
keywords:
- nats
- streaming
- stan
- delivery
- ratelimit
- replay
- statefulset
- cncf
maintainers:
- email: wally@nats.io
  name: Waldemar Quevedo
- email: colin@nats.io
  name: Colin Sullivan
- name: rchenzheng
name: stan
version: 0.4.0
